/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package richtercloud.reflection.form.builder;

import java.lang.reflect.Field;
import java.util.HashMap;
import java.util.Map;
import javax.swing.JComponent;

/**
 *
 * @author richter
 * @param <E> a generic type for the entity class
 */
public class ReflectionFormPanel<E> extends javax.swing.JPanel {
    private static final long serialVersionUID = 1L;
    private Map<Field, JComponent> fieldMapping = new HashMap<>();
    private Map<Class<? extends JComponent>, ValueRetriever<?, ?>> valueRetrieverMapping;
    private E instance;

    /**
     * Creates new form ReflectionFormPanel
     */
    public ReflectionFormPanel() {
        initComponents();
    }

    public ReflectionFormPanel(Map<Field, JComponent> fieldMapping, E instance, Map<Class<? extends JComponent>, ValueRetriever<?, ?>> valueRetrieverMapping) {
        this();
        if(instance == null) {
            throw new IllegalArgumentException("instance mustn't be null");
        }
        this.fieldMapping = fieldMapping;
        this.valueRetrieverMapping = valueRetrieverMapping;
        this.instance = instance;
    }

    public JComponent getComponentByField(Field field) {
        return this.fieldMapping.get(field);
    }

    public void updateInstance() throws IllegalArgumentException, IllegalAccessException {
        for(Field field : fieldMapping.keySet()) {
            JComponent comp = fieldMapping.get(field);
            //figure out what type comp is supposed to deliver
            ValueRetriever valueRetriever = this.valueRetrieverMapping.get(comp);
            Object value = valueRetriever.retrieve(comp);
            field.set(instance, value);
        }
    }

    public E retrieveInstance() throws IllegalArgumentException, IllegalAccessException {
        updateInstance();
        return instance;
    }

    public Map<Class<? extends JComponent>, ValueRetriever<?, ?>> getValueRetrieverMapping() {
        return valueRetrieverMapping;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
